require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CircuitsController do

  def mock_circuit(stubs={})
    @mock_circuit ||= mock_model(Circuit, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all circuits as @circuits" do
      Circuit.stub(:all) { [mock_circuit] }
      get :index
      assigns(:circuits).should eq([mock_circuit])
    end
  end

  describe "GET show" do
    it "assigns the requested circuit as @circuit" do
      Circuit.stub(:find).with("37") { mock_circuit }
      get :show, :id => "37"
      assigns(:circuit).should be(mock_circuit)
    end
  end

  describe "GET new" do
    it "assigns a new circuit as @circuit" do
      Circuit.stub(:new) { mock_circuit }
      get :new
      assigns(:circuit).should be(mock_circuit)
    end
  end

  describe "GET edit" do
    it "assigns the requested circuit as @circuit" do
      Circuit.stub(:find).with("37") { mock_circuit }
      get :edit, :id => "37"
      assigns(:circuit).should be(mock_circuit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created circuit as @circuit" do
        Circuit.stub(:new).with({'these' => 'params'}) { mock_circuit(:save => true) }
        post :create, :circuit => {'these' => 'params'}
        assigns(:circuit).should be(mock_circuit)
      end

      it "redirects to the created circuit" do
        Circuit.stub(:new) { mock_circuit(:save => true) }
        post :create, :circuit => {}
        response.should redirect_to(circuit_url(mock_circuit))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved circuit as @circuit" do
        Circuit.stub(:new).with({'these' => 'params'}) { mock_circuit(:save => false) }
        post :create, :circuit => {'these' => 'params'}
        assigns(:circuit).should be(mock_circuit)
      end

      it "re-renders the 'new' template" do
        Circuit.stub(:new) { mock_circuit(:save => false) }
        post :create, :circuit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested circuit" do
        Circuit.stub(:find).with("37") { mock_circuit }
        mock_circuit.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :circuit => {'these' => 'params'}
      end

      it "assigns the requested circuit as @circuit" do
        Circuit.stub(:find) { mock_circuit(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:circuit).should be(mock_circuit)
      end

      it "redirects to the circuit" do
        Circuit.stub(:find) { mock_circuit(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(circuit_url(mock_circuit))
      end
    end

    describe "with invalid params" do
      it "assigns the circuit as @circuit" do
        Circuit.stub(:find) { mock_circuit(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:circuit).should be(mock_circuit)
      end

      it "re-renders the 'edit' template" do
        Circuit.stub(:find) { mock_circuit(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested circuit" do
      Circuit.stub(:find).with("37") { mock_circuit }
      mock_circuit.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the circuits list" do
      Circuit.stub(:find) { mock_circuit }
      delete :destroy, :id => "1"
      response.should redirect_to(circuits_url)
    end
  end

end
