require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GatesController do

  # This should return the minimal set of attributes required to create a valid
  # Gate. As you add validations to Gate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => 'the gate',
     :token => 'z',
     :image => "12345"}
  end

  describe "GET index" do
    it "assigns all gates as @gates" do
      gate = Gate.create! valid_attributes
      get :index
      assigns(:gates).should eq([gate])
    end
  end

  describe "GET show" do
    it "assigns the requested gate as @gate" do
      gate = Gate.create! valid_attributes
      get :show, :id => gate.id.to_s
      assigns(:gate).should eq(gate)
    end
  end

  describe "GET new" do
    it "assigns a new gate as @gate" do
      get :new
      assigns(:gate).should be_a_new(Gate)
    end
  end

  describe "GET edit" do
    it "assigns the requested gate as @gate" do
      gate = Gate.create! valid_attributes
      get :edit, :id => gate.id.to_s
      assigns(:gate).should eq(gate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gate" do
        expect {
          post :create, :gate => valid_attributes
        }.to change(Gate, :count).by(1)
      end

      it "assigns a newly created gate as @gate" do
        post :create, :gate => valid_attributes
        assigns(:gate).should be_a(Gate)
        assigns(:gate).should be_persisted
      end

      it "redirects to the created gate" do
        post :create, :gate => valid_attributes
        response.should redirect_to(Gate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gate as @gate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gate.any_instance.stub(:save).and_return(false)
        post :create, :gate => {}
        assigns(:gate).should be_a_new(Gate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gate.any_instance.stub(:save).and_return(false)
        post :create, :gate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gate" do
        gate = Gate.create! valid_attributes
        # Assuming there are no other gates in the database, this
        # specifies that the Gate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => gate.id, :gate => {'these' => 'params'}
      end

      it "assigns the requested gate as @gate" do
        gate = Gate.create! valid_attributes
        put :update, :id => gate.id, :gate => valid_attributes
        assigns(:gate).should eq(gate)
      end

      it "redirects to the gate" do
        gate = Gate.create! valid_attributes
        put :update, :id => gate.id, :gate => valid_attributes
        response.should redirect_to(gate)
      end
    end

    describe "with invalid params" do
      it "assigns the gate as @gate" do
        gate = Gate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gate.any_instance.stub(:save).and_return(false)
        put :update, :id => gate.id.to_s, :gate => {}
        assigns(:gate).should eq(gate)
      end

      it "re-renders the 'edit' template" do
        gate = Gate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gate.any_instance.stub(:save).and_return(false)
        put :update, :id => gate.id.to_s, :gate => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gate" do
      gate = Gate.create! valid_attributes
      expect {
        delete :destroy, :id => gate.id.to_s
      }.to change(Gate, :count).by(-1)
    end

    it "redirects to the gates list" do
      gate = Gate.create! valid_attributes
      delete :destroy, :id => gate.id.to_s
      response.should redirect_to(gates_url)
    end
  end

end
