require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpecificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Specification. As you add validations to Specification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all specifications as @specifications" do
      specification = Specification.create! valid_attributes
      get :index
      assigns(:specifications).should eq([specification])
    end
  end

  describe "GET show" do
    it "assigns the requested specification as @specification" do
      specification = Specification.create! valid_attributes
      get :show, :id => specification.id
      assigns(:specification).should eq(specification)
    end
  end

  describe "GET new" do
    it "assigns a new specification as @specification" do
      get :new
      assigns(:specification).should be_a_new(Specification)
    end
  end

  describe "GET edit" do
    it "assigns the requested specification as @specification" do
      specification = Specification.create! valid_attributes
      get :edit, :id => specification.id
      assigns(:specification).should eq(specification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Specification" do
        expect {
          post :create, :specification => valid_attributes
        }.to change(Specification, :count).by(1)
      end

      it "assigns a newly created specification as @specification" do
        post :create, :specification => valid_attributes
        assigns(:specification).should be_a(Specification)
        assigns(:specification).should be_persisted
      end

      it "redirects to the created specification" do
        post :create, :specification => valid_attributes
        response.should redirect_to(Specification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved specification as @specification" do
        # Trigger the behavior that occurs when invalid params are submitted
        Specification.any_instance.stub(:save).and_return(false)
        post :create, :specification => {}
        assigns(:specification).should be_a_new(Specification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Specification.any_instance.stub(:save).and_return(false)
        post :create, :specification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested specification" do
        specification = Specification.create! valid_attributes
        # Assuming there are no other specifications in the database, this
        # specifies that the Specification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Specification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => specification.id, :specification => {'these' => 'params'}
      end

      it "assigns the requested specification as @specification" do
        specification = Specification.create! valid_attributes
        put :update, :id => specification.id, :specification => valid_attributes
        assigns(:specification).should eq(specification)
      end

      it "redirects to the specification" do
        specification = Specification.create! valid_attributes
        put :update, :id => specification.id, :specification => valid_attributes
        response.should redirect_to(specification)
      end
    end

    describe "with invalid params" do
      it "assigns the specification as @specification" do
        specification = Specification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Specification.any_instance.stub(:save).and_return(false)
        put :update, :id => specification.id, :specification => {}
        assigns(:specification).should eq(specification)
      end

      it "re-renders the 'edit' template" do
        specification = Specification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Specification.any_instance.stub(:save).and_return(false)
        put :update, :id => specification.id, :specification => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested specification" do
      specification = Specification.create! valid_attributes
      expect {
        delete :destroy, :id => specification.id
      }.to change(Specification, :count).by(-1)
    end

    it "redirects to the specifications list" do
      specification = Specification.create! valid_attributes
      delete :destroy, :id => specification.id
      response.should redirect_to(specifications_url)
    end
  end

end
